### ISSUE TITLE
pip install panml failure

### ISSUE THREAD

**Issue by hamin123** [Pan-ML/panml#35] opened 2023-05-28 10:06 UTC
pip install panml fails as follows :- 
Collecting panml
  Using cached panml-0.0.18.tar.gz (23 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [10 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\GNG\AppData\Local\Temp\pip-install-zxwy469_\panml_4b9a7fee4cf34bdf9dd520fccfc48a19\setup.py", line 6, in <module>
      long_description = (this_directory / "README.md").read_text()
    File "C:\Users\GNG\.conda\envs\panml\lib\pathlib.py", line 1135, in read_text
      return f.read()
    File "C:\Users\GNG\.conda\envs\panml\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2778: character maps to <undefined>
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by wanoz** [comment] 2023-05-28 10:35
Good find. Thanks for pointing this out. I think the issue is related to the setup.py not reading in the README.md properly. 

Currently it's this:
this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text()

We can probably resolve the issue if we change the encoding to "utf8":
this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text(encoding="utf-8")

I'll make this change and push through the update today or tomorrow.

Cheers

**Comment by wanoz** [comment] 2023-05-28 12:50
Fix has been issued in v0.0.19

**Closed** 2023-05-28 12:50 UTC
